modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "yesserusers_ice_cream_mod"
version = "${version}"
displayName = "Yesseruser's Ice Cream Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.yesserusers_ice_cream_mod]]
modId = "neoforge"
type = "required"
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_ice_cream_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_ice_cream_mod]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "yesserusers_ice_cream_mod.mixins.json"
