modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/yesseruser/yesserusers-ice-cream-mod/issues"
license = "MIT"

[[mods]]
modId = "yesserusers_ice_cream_mod"
version = "${version}"
displayName = "Yesseruser's Ice Cream Mod"
authors = "yesseruser"
description = '''
A simple ice cream mod. Adds multiple ice creams that can be crafted and eaten.
'''
#logoFile = ""

[[dependencies.yesserusers_ice_cream_mod]]
modId = "neoforge"
type = "required"
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_ice_cream_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_ice_cream_mod]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "yesserusers_ice_cream_mod.mixins.json"
