modLoader = "javafml"
loaderVersion = "[1.0,)"
issueTrackerURL = "https://github.com/yesseruser/yesserusers-ice-cream-mod/issues"
license = "MIT"

[[mods]]
modId = "yesserusers_ice_cream_mod"
version = "${version}"
displayName = "Yesseruser's Ice Cream Mod"
authors = "yesseruser"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.yesserusers_ice_cream_mod]]
modId = "neoforge"
type = "required"
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_ice_cream_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_ice_cream_mod]]
modId = "architectury"
type = "required"
versionRange = "[*,)"
ordering = "AFTER"
side = "BOTH"
